# Generated by Django 5.2.6 on 2026-02-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('smart_process_entity_type_id', models.IntegerField(blank=True, null=True)),
                ('smart_process_item_id', models.IntegerField(blank=True, null=True)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
                ('last_message_date', models.DateTimeField(blank=True, null=True)),
                ('messages_count', models.PositiveIntegerField(default=0)),
                ('last_sender', models.CharField(blank=True, default='', max_length=255)),
                ('last_subject', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='email_smartprocess.emailthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
