# Generated by Django 5.2.6 on 2026-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_smartprocess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='cc_emails',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='to_emails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
